version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: Install Maven and Ant
          command: |
            sudo apt-get update && sudo apt-get install -y ant maven
      - run:
          name: Build the project
          command: |
            cd dependencies
            ant
            cd ..
            mvn clean package

workflows:
  build-workflow:
    jobs:
      - build